import type { AppDefinition, AppId } from '../../../shared/types/desktop';

export const applicationCatalog: AppDefinition[] = [
  {
    id: 'portfolio',
    icon: 'profile',
    title: 'Обо мне',
    shortTitle: 'Обо мне',
    subtitle: 'Профиль, специализация и контакты',
    tint: '#ac2954',
    defaultSize: { width: 1480, height: 900 },
    minSize: { width: 1040, height: 720 },
    launchLabel: 'Портфолио',
  },
  {
    id: 'projects',
    icon: 'briefcase',
    title: 'Репозитории',
    shortTitle: 'Репо',
    subtitle: 'GitHub-проекты и актуальные ссылки',
    tint: '#ffb36b',
    defaultSize: { width: 980, height: 640 },
    minSize: { width: 760, height: 520 },
    launchLabel: 'GitHub',
  },
  {
    id: 'blog',
    icon: 'article',
    title: 'Блог',
    shortTitle: 'Блог',
    subtitle: 'Посты и разборы из Telegram-канала',
    tint: '#ffd16d',
    defaultSize: { width: 1080, height: 680 },
    minSize: { width: 820, height: 560 },
    launchLabel: 'Читать',
  },
  {
    id: 'system',
    icon: 'system',
    title: 'О системе',
    shortTitle: 'Система',
    subtitle: 'Это ты: браузер, устройство и поддержка веб-возможностей',
    tint: '#79e5d2',
    defaultSize: { width: 960, height: 640 },
    minSize: { width: 760, height: 540 },
    launchLabel: 'Паспорт',
  },
  {
    id: 'contact',
    icon: 'mail',
    title: 'Контакты',
    shortTitle: 'Связь',
    subtitle: 'Куда писать и где смотреть материалы',
    tint: '#ff8aa7',
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 580, height: 420 },
    launchLabel: 'Написать',
  },
  {
    id: 'neon-xo',
    icon: 'gamepad',
    title: 'Неон XO',
    shortTitle: 'XO',
    subtitle: 'Мини-игра: крестики против модели',
    tint: '#ff79ab',
    defaultSize: { width: 700, height: 600 },
    minSize: { width: 560, height: 500 },
    launchLabel: 'Играть',
  },
  {
    id: 'signal-hunt',
    icon: 'target',
    title: 'Сигнал-хант',
    shortTitle: 'Signal',
    subtitle: 'Мини-игра на реакцию',
    tint: '#6df0d7',
    defaultSize: { width: 760, height: 620 },
    minSize: { width: 620, height: 520 },
    launchLabel: 'Играть',
  },
];

export function getApplication(appId: AppId) {
  return applicationCatalog.find((app) => app.id === appId)!;
}
